{{- if .Values.db.mongoUri }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  labels:
    app.kubernetes.io/name: {{ .Values.db.secretName }}
    app.kubernetes.io/component: membership
    app.kubernetes.io/part-of: server-scan
type: Opaque
stringData:
  {{ .Values.db.mongoUriKey }}: {{ .Values.db.mongoUri | quote }}
{{- end }}
---
{{- if .Values.db.cursorSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.cursorSecretName }}
  labels:
    app.kubernetes.io/name: {{ .Values.db.cursorSecretName }}
    app.kubernetes.io/component: membership
    app.kubernetes.io/part-of: server-scan
type: Opaque
stringData:
  {{ .Values.db.cursorSecretKey }}: {{ .Values.db.cursorSecret | quote }}
{{- end }}
