{{- if and .Values.nodes.ssh.enabled .Values.nodes.ssh.privateKey (not .Values.nodes.ssh.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nodes-ssh
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-nodes-ssh
    app.kubernetes.io/component: membership
    app.kubernetes.io/part-of: server-scan
type: Opaque
stringData:
  {{ .Values.nodes.ssh.secretKey }}: {{ .Values.nodes.ssh.privateKey | quote }}
{{- end }}
