{{- $mongoExternal := and (not .Values.mongodb.enabled) .Values.db.mongoUri }}
{{- $redisExternal := and (not .Values.redis.enabled) .Values.db.redisUri }}
{{- if or $mongoExternal $redisExternal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  labels:
    app.kubernetes.io/name: {{ .Values.db.secretName }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: server-scan
type: Opaque
stringData:
  {{- if $mongoExternal }}
  mongo-uri: {{ .Values.db.mongoUri | quote }}
  {{- end }}
  {{- if $redisExternal }}
  redis-uri: {{ .Values.db.redisUri | quote }}
  {{- end }}
{{- end }}
