{{- if and .Values.frontend.enabled .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: server-scan
spec:
  {{- with .Values.route.host }}
  host: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
